### ISSUE TITLE
Give participants access to Nebari and the dataset hosted on GCS

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/presentations#14]
We need to give PyCon participants access to:

-  A Nebari instance, our options are:
    - Use `nebari.quansight.dev`: Allow participants to login at the tutorial, and automatically put them in a `pycon-2023` group. This group will need to have access to Dask.
    - (if the above is not possible) Crete a new Nebari instance, maybe `demo.nebari.dev` which we can tear down after the tutorial. Again, we'll need people to be able to login during the tutorial.
    - For reference, at PyData NYC, participants could login with any name and email for ~2 days of the tutorial

- [Airline-ontime-performance](https://console.cloud.google.com/storage/browser/quansight-datasets/airline-ontime-performance?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false) dataset hosted on GCP, options:
    - Get read-only credentials for this bucket, and have it in the shared folder for all participants,
    - Make this folder/bucket publically readable for the tutorial duration.
    
cc @dharhas

**Comment by pavithraes** [comment]
@iameskild @costrouc @viniciusdc Will you be able to help with this?

**Comment by dharhas** [comment]
- users will sign up at the event and need ability to spin up dask clusters
- not exactly sure on total number of needed dask workers yet but probably at lets assume 10 workers each x 40 participants or 400-600 workers.

**Comment by dharhas** [comment]
If we setup the bucket as public read-only + requestor-pays would we be able to use it from our nebari instance without credentials?

**Comment by pavithraes** [comment]
> not exactly sure on total number

I'll reach out to the PyCon organizers about the actual number of registered participants

**Comment by viniciusdc** [comment]
@pavithraes @dharhas I am not sure about other ocasions but I can see two options, that I have testes so far.

**Comment by dharhas** [comment]
@viniciusdc we want automated self registration. We won't know who is attending beforehand. But we need it to only be open during the event.

**Comment by costrouc** [comment]
- For simplicity add the dask role to the `analyst` group. 
 - [X] Make a quansight group that all quansight people are a member of. Move everything in analyst folder to quansight folder
 -  [X] Create pycon2023 group. Group needs to have dask permissions.
 - [ ] Make bucket quansight-datasets publicly readable
 - [ ] Make all gpu profiles in nebari-quansight-deployment restricted to quansight group

**Comment by costrouc** [comment]
@viniciusdc modify https://github.com/Quansight/infra-quansight-datasets/blob/main/main.tf#L24-L27 to make the bucket publicly readable. I think you should use https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_iam with `member=allUsers`  and role `role = "roles/storage.objectViewer"`

**Comment by iameskild** [comment]
@pavithraes @dharhas the `quansight-datasets` bucket should now be publicly readable. 

I just tested this out:
```python
import gcsfs
gs = gcsfs.GCSFileSystem(token="anon")
bucket = "gs://quansight-datasets"
print(gs.ls(bucket))
---
['quansight-datasets/airline-ontime-performance', 'quansight-datasets/test', 'quansight-datasets/test']
```
