### ISSUE TITLE
Updates to `nebari.quansight.dev` for PyCon

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/presentations#27]
Note that all of these are "nice-to-haves", and not blockers. 

In order of priority:

1. We want to make sure the default machine for Dask workers (Gateway options) is a small/medium instance, currently we see a "GPU-worker" instance selected by default:

![Screenshot 2023-04-13 at 7 09 12 PM](https://user-images.githubusercontent.com/33131404/231776873-052d9562-1bf0-42ac-84e0-5a18e4541c38.png)

Dharhas said the "GPU-worker" was added for a demo and can be removed altogether from gateway options.

2. We'd like to try using a large (8-core, 32GB) instance. If we can get access to it, we can test to see if it makes any difference over the next few days, and have time to remove it on Monday if needed.

3. We see the Dask JupyterLab extension having some bugs where it gets stuck after a compute and needs to be refreshed. A newer version of the extension might be able to fix this. We can test a newer version separately to see it if helps and make sure it doesn't break anything. This is low priority because the current setup works and we'd prefer a stable Nebari over the newest extension version. :)

@Eskild will you be able to help us with these?

cc @dharhas

**Comment by dharhas** [comment]
- lets make 'medium' the default profile and maybe make 'pycon/pycon-tutorial' the default conda env if its easy.
- lets add the large instance to the dask-workers as well just for testing
- if we are running the latest extension, let's leave it as is. the workaround (switch away from plot tab and come back, isn't terrible)

**Comment by dharhas** [comment]
also as an fyi. we should be able to launch daskgateway clusters from the extension. let me find the link.

**Comment by iameskild** [comment]
Okay reordering the profiles appears to be trickier than I thought; they appear in alphabetical order by default. That said, I believe I have the "GPU Worker k80" working. I can spin up a dask worker that runs on a tesla k80. 

Lastly, the large instance has been added to both the user and worker profiles and I've moved all of the global conda-store environments to the quansight namespace. The exception is `pycon2023`.

**Comment by dharhas** [comment]
we can delete the 'global/pycon2023'. yeah I remember the alphabetical thing. A while back I think we prepended envs with '01', '02' etc to fix for another tutorial.

We can close this issue. I will open another if we have more tweaks..

**Comment by iameskild** [comment]
Final updates for nebari.quansight.dev based on stress-test meeting:
- [ ] remove execute time jlab extention
- [ ] increase `max_nodes` for k80 x1 to 50
- [ ] hide `Large Instance` profile from pycon attendees

Then after the deployment, we need to update:
- [ ] keycloak - to ensure new registrants are added to the  `pycon2023` group
- [ ] etc-jupyter configmap - to add a named Jitsi room
