### ISSUE TITLE
Configure default rooms for jitsi videochat plugiin.

### ISSUE THREAD

**Issue by dharhas** [nebari-dev/presentations#28]
@iameskild can you look into the feasibility of configuring named jitsi rooms in jupyter video chat.

https://github.com/jupyterlab-contrib/jupyter-videochat

```
{
  "VideoChat": {
    "room_prefix": "our-spiffy-room-prefix",
    "rooms": [
      {
        "id": "stand-up",
        "displayName": "Stand-Up",
        "description": "Daily room for meeting with the team"
      },
      {
        "id": "all-hands",
        "displayName": "All-Hands",
        "description": "A weekly room for the whole team"
      }
    ],
    "jitsi_server": "jitsi.example.com"
  }
}
```

It its easy, I'd like to make a room called `bigdata-tutorial-pycon2023` or similar.

I assume the room will show up in the `select room to join` section below.

![image](https://user-images.githubusercontent.com/561301/232054757-4f3137fc-8cc6-4ed1-aeea-2b544a825627.png)

**Comment by iameskild** [comment]
@dharhas @pavithraes  I think this is possible if we modify the jupyter_notebook_config ([here](https://github.com/nebari-dev/nebari/blob/develop/nebari/template/stages/07-kubernetes-services/modules/kubernetes/services/jupyterhub/files/jupyter/jupyter_notebook_config.py.tpl)) but this would require running the cluster from off of a specific commit. 

We could also modify the `etc-jupyter` configmap (which hosts this config file) directly and see if it works; just an FYI any deployment would wipe away these changes.

**Comment by iameskild** [comment]
@dharhas @pavithraes The workaround I described above is possible if we modify the `jupyter_notebook_config` with the following:

```python
    c.VideoChat.rooms = [
        {
            "id": "pycon2023",
            "displayName": "pycon2023",
            "description": "this is a test",
        },
    ]
```

<img width="532" alt="Screenshot 2023-04-14 at 10 52 22" src="https://user-images.githubusercontent.com/42120229/232120720-c4aedac4-290e-4d98-bc28-2601a23157c5.png">

**Comment by dharhas** [comment]
Let's use:

```
    c.VideoChat.rooms = [
        {
            "id": "pycon2023-bigdata-tutorial",
            "displayName": "PyCon 2023",
            "description": "Data of an Unusual Size Tutorial",
        },
    ]
```

**Comment by pavithraes** [comment]
This is complete, thanks folks!
